openapi: 3.0.0
info:
  title: Finist API
  version: 1.0

servers:
  - url: http://localhost:8080
    description: Server is running on se.ifmo.ru but access through port forwarding on localhost.

paths:
  /users:
  /compititions:
